/**
 * Domain-level error codes surfaced in API error responses.
 * Using string constants (not numeric) keeps responses self-documenting
 * and stable across API versions regardless of ordering changes.
 */
export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REUSED: 'AUTH_TOKEN_REUSED',
  AUTH_INSUFFICIENT_SCOPE: 'AUTH_INSUFFICIENT_SCOPE',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ORGANIZATION_ACCESS: 'FORBIDDEN_ORGANIZATION_ACCESS',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Entitlements and access
  FEATURE_NOT_INCLUDED: 'FEATURE_NOT_INCLUDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  SEAT_LIMIT_REACHED: 'SEAT_LIMIT_REACHED',
  ENTITLEMENT_SNAPSHOT_MISSING: 'ENTITLEMENT_SNAPSHOT_MISSING',

  // Overrides
  OVERRIDE_NOT_FOUND: 'OVERRIDE_NOT_FOUND',
  OVERRIDE_DATE_RANGE_INVALID: 'OVERRIDE_DATE_RANGE_INVALID',
  OVERRIDE_CONFLICT: 'OVERRIDE_CONFLICT',

  // Usage
  DUPLICATE_USAGE_EVENT: 'DUPLICATE_USAGE_EVENT',

  // Subscriptions
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_PLAN_INACTIVE: 'SUBSCRIPTION_PLAN_INACTIVE',
  SUBSCRIPTION_ADDON_DUPLICATE: 'SUBSCRIPTION_ADDON_DUPLICATE',
  SUBSCRIPTION_ADDON_NOT_FOUND: 'SUBSCRIPTION_ADDON_NOT_FOUND',
  SUBSCRIPTION_CANNOT_MODIFY: 'SUBSCRIPTION_CANNOT_MODIFY',

  // Catalog
  CATALOG_FEATURE_NOT_FOUND: 'CATALOG_FEATURE_NOT_FOUND',
  CATALOG_DUPLICATE_FEATURE_CODE: 'CATALOG_DUPLICATE_FEATURE_CODE',
  CATALOG_PLAN_NOT_FOUND: 'CATALOG_PLAN_NOT_FOUND',
  CATALOG_DUPLICATE_PLAN_SLUG: 'CATALOG_DUPLICATE_PLAN_SLUG',
  CATALOG_ADDON_NOT_FOUND: 'CATALOG_ADDON_NOT_FOUND',
  CATALOG_DUPLICATE_ADDON_SLUG: 'CATALOG_DUPLICATE_ADDON_SLUG',
  CATALOG_DUPLICATE_FEATURE_MAPPING: 'CATALOG_DUPLICATE_FEATURE_MAPPING',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
